######################################################################
#  Project Makefile
######################################################################

BINARY		= test_flash
SRCFILES	= test_flash.c winbond.c 
LDSCRIPT	= ../stm32f103c8t6.ld

# DEPS		= 	# Any additional dependencies for your build
# CLOBBER	+= 	# Any additional files to be removed with "make clobber"

SEMIHOSTING	= 0
OOCD_BOARD	?= target/stm32f1x.cfg

include ../Makefile.include
######################################################################
